### ISSUE TITLE
Roadmap to v1.0?

### ISSUE THREAD

**Issue by Veramone** [emmanueltouzery/prelude-ts#32]
Hello!

First of all, I love your library. It offers exactly what others don't for me and the typings are just _good_. 

I was wondering if there's a roadmap to a v1 release? (if you're even planning on doing one)

I'm already using this in production, but some team members have expressed concerns about the lack of a `v1.0.0`. I would love to contribute if possible!

Regards,

**Comment by emmanueltouzery** [comment]
Hi, nice to hear! Actually I'm happy with prelude-ts as it is. Maybe some new collection types could be added (probably not by me though), and if typescript changes, I'd want to track that. I also have a little thing I'd like to do: clean up the npm package, because looking on npm you'd think the library is multi-megabyte and bloated. It's because apidocs and tests and other things are in there.

So if that matters to people, maybe I do that and ship a 1.0!

**Comment by Veramone** [comment]
Sounds great! If there's anything at all you'd like some help with feel free to ping me :) It's about time I start jumping into FOSS collaboration, even if it's small things.

Feel free to close this issue if you'd prefer :)

**Comment by emmanueltouzery** [comment]
1.0.0 was released and is now available on npm!
