### ISSUE TITLE
Are ideas, PRs accepted?

### ISSUE THREAD

**Issue by aleksei-berezkin** [emmanueltouzery/prelude-ts#33]
Hi, first I'd like to say your great lib is a real relief after all these unnatural for TS `X.compose(..., ...)(data)`. Operating collections in Scala-style is a real pleasure. That's huge and valuable work, thanks.

Now the question is — do you welcome suggestions and code? If you do, I'd create issues whenever I have an idea (I have some), so they can be discussed; then proceed with PR if an idea is accepted. What are your thoughts?

**Comment by emmanueltouzery** [comment]
I'm glad you like it! About suggestions and PRs: Yes please! And as you said it's probably better if you first make a suggestion before investing lots of your time in a PR that I may reject on conceptual grounds or because I think it's out of scope for prelude.

So yes, please mention your ideas, I'm interested, especially if you're ready to submit PRs for them!

**Comment by aleksei-berezkin** [comment]
Thanks for quick answer! Closing this issue as the answer is clear.
